### PR TITLE
Add AppArmor profiles for SGOS

### PR DESCRIPTION
**Pull request by ioerror**
I collected all the aa profiles I created ages ago - they are a start - this also needs a debian/ directory - but I've left that up to someone else for now.

I'll test each config against the current sgos release and make additional changes to my repo for any changes that I need.

### CODE REVIEW

**Comment by Phoul** [comment]
Running these new profiles, I've encountered one issue so far:

audit: type=1400 audit(1458862088.571:113): apparmor="DENIED" operation="mkdir" profile="/usr/sbin/NetworkManager" name="/run/NetworkManager/" pid=1502 comm="NetworkManager" requested_mask="c" denied_mask="c" fsuid=0 ouid=0

This prevents NetworkManager from starting successfully. If I get a bit more time, will look into which directories its attempting to create.

**Comment by ioerror** [comment]
The NetworkManager policy should be updated to ensure it can make files in /run/NetworkManager of course...

**Comment by ioerror** [comment]
@Phoul have you tried all of the profiles? If so: have you had any exceptions or errors or denials?

**Comment by Phoul** [comment]
So far, just the one relating to NetworkManager. 

I did not encounter any other obvious issues, however I only did a few hours of testing with them. I will pull down the updated profile for NetworkManager and continue to run with the other profiles, to see if I encounter any other issues.

**Comment by ioerror** [comment]
Please do try all of these by running for `aa-enforce` each one.

**Comment by ioerror** [comment]
I'm running all of these without any issues at all.

**Pull request merged**
